name = "DiskDetection"
uuid = "72f87620-1546-45cd-8031-1f00e49166d6"
authors = ["Riccardo Foffi <rfoffi@ethz.ch> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
